[project]
name = "ebc-payments"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "pandas-stubs==2.3.2.250926",
    "typer>=0.20.0",
]
